# Grader Configuration
# Usage: python main.py --config grader_config.yml

# Base paths
# source_path used as root for readme, tests, and test_data
# source_path: "Test_Sources"
# source_path: "/home/olmozavala/Dropbox/MyCourses/FSU/ISC_4933_5935_DataScience_meets_HealthSciences/Homeworks/Template_Lab01_GithubBasics"
source_path: "/home/olmozavala/Dropbox/MyCourses/FSU/ISC_4933_5935_DataScience_meets_HealthSciences/Homeworks/Template_Lab02_PythonOverview"

# Dependent paths (relative to source_path)
readme_path: "README.md"
tests_dir: "tests"
test_data_dir: "test_folder"

# Root-relative paths 
submissions_dir: "/home/olmozavala/Dropbox/MyCourses/FSU/ISC_4933_5935_DataScience_meets_HealthSciences/SEMESTERS/Spring_2026/StudentHomerworks/lab-02-python-overview-submissions"
grades_dir: "/home/olmozavala/Dropbox/MyCourses/FSU/ISC_4933_5935_DataScience_meets_HealthSciences/SEMESTERS/Spring_2026/StudentHomerworks/lab-02-python-overview-submissions/GRADES"

# Execution flags
only_dashboard: false # Launch dashboard with existing grades (skip grading)
verbose: true

# Dashboard settings
dashboard_port: 8053